# Model Settings
model_label: "Model"
model_value: "SIR"
model_options:
  - label: "SEIR"
    value: "SEIR"
  - label: "SIR"
    value: "SIR"
  - label: "SEIS"
    value: "SEIS"
  - label: "SIS"
    value: "SIS"
  - label: "SEI"
    value: "SEI"
  - label: "SI"
    value: "SI"

# Seed Settings
seed_label: "Seed"
seed_min: 0
seed_step: 1
seed_value: 0

# Trial Settings
trials_label: "Trials"
trials_min: 1
trials_step: 1
trials_value: 1

# Population Settings
population_label: "Population"
population_min: 0
population_step: 1
population_value: 1000

# Arrivals Settings
arrivals_label: "Arrivals"
arrivals_min: 0
arrivals_step: 1
arrivals_value: 0

# Initial Infection Chance Settings
infection_initial_label: "Initial Infection"
infection_initial_min: 0
infection_initial_max: 1
infection_initial_step: 0.01
infection_initial_value: 0.1

# Infection Strength Settings
infection_strength_label: "Infection Strength"
infection_strength_min: 0.0
infection_strength_max: 2.0
infection_strength_step: 0.01
infection_strength_value: 1.0

infection_strength_start_value: 0.5
infection_strength_stop_value: 1.5

# Infection Radius Settings
infection_radius_label: "Infection Radius"
infection_radius_min: 0.0
infection_radius_max: 20.0
infection_radius_step: 0.01
infection_radius_value: 10.0

infection_radius_start_value: 5.0
infection_radius_stop_value: 15.0

# Incubation Mean Settings
incubation_mean_label: "Incubation Mean"
incubation_mean_min: 0.0
incubation_mean_max: 336.0
incubation_mean_step: 0.01
incubation_mean_value: 168.0

# Incubation Shape Settings
incubation_shape_label: "Incubation Shape"
incubation_shape_min: 0.0
incubation_shape_max: 20.0
incubation_shape_step: 0.01
incubation_shape_value: 10.0

# Infection Mean Settings
infection_mean_label: "Infection Mean"
infection_mean_min: 0.0
infection_mean_max: 336.0
infection_mean_step: 0.01
infection_mean_value: 168.0

infection_mean_start_value: 84.0
infection_mean_stop_value: 252.0

# Infection Shape Settings
infection_shape_label: "Infection Shape"
infection_shape_min: 0.0
infection_shape_max: 20.0
infection_shape_step: 0.01
infection_shape_value: 10.0

infection_shape_start_value: 5.0
infection_shape_stop_value: 15.0

#Intervention Start Settings
intervention_start_label: "Intervention Start"
intervention_start_min: 0
intervention_start_max: 540
intervention_start_step: 1
intervention_start_value: 0

#Intervention Stop Settings
intervention_stop_label: "Intervention Stop"
intervention_stop_min: 0
intervention_stop_max: 540
intervention_stop_step: 1
intervention_stop_value: 0

# Intervention Strength Settings
intervention_strength_label: "Intervention Strength"
intervention_strength_min: 0.0
intervention_strength_max: 1.0
intervention_strength_step: 0.01
intervention_strength_value: 0.5

# Parameter Choice Settings
parameter_label: "Parameters"
parameter_value: ""
parameter_options:
  - label: "Strength"
    value: "strength"
  - label: "Radius"
    value: "radius"
  - label: "Duration Mean"
    value: "duration-mean"
  - label: "Duration Shape"
    value: "duration-shape"

# Resolution Settings
resolution_label: "Resolution"
resolution_min: 0
resolution_step: 1
resolution_value: 10